name: Run all tests API

on: [push, workflow_dispatch]

jobs: 

  build:
  
    runs-on: windows-latest
    
    steps:
      
      - name: Get code from repository
        uses: actions/checkout@v3
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Display Python version
        run: python -V
        
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip3 install pathlib
          pip3 install pytest
          pip3 install requests
          pip3 install allure-pytest
          pip3 install win_unicode_console
        continue-on-error: true
      
      - name: Run API tests
        run: |
          python -Bc "for p in __import__('pathlib').Path('.').rglob('*.py[co]'): p.unlink()"
          python -Bc "for p in __import__('pathlib').Path('.').rglob('__pycache__'): p.rmdir()"
          python -m pytest -s -v
    
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: my-logs
          path: logs/
          
      - name: Download logs
        uses: actions/download-artifact@v3
        with:
          name: my-logs
